app.py
from flask import Flask, request, redirect, url_for, render_template
from src.db.config import database_connection, initialize_database
from src.db.query import nav

from src.routes import run, team, member
import json

app = Flask(__name__) # handles it all
app.config.from_file('./etc/config.json', load=json.load)

# create the tables if they dont exist
with app.app_context():
    initialize_database(app)


app.register_blueprint(member.routes)
app.register_blueprint(team.routes)
app.register_blueprint(run.routes)


@app.get('/') # index = home page
def index():
    database = database_connection(app)

    return render_template(
        'index.html', 
        page='Dashboard',
        nav=nav(database),
        version=app.config['VERSION'], 
        error=request.args.get('error'),
        modal=request.args.get('modal'),
        edit=request.args.get('edit')
    )

src/routes/member.py
from src.db.config import database_connection
from src.db.member import create

from flask import Blueprint, request, redirect, url_for, current_app


routes = Blueprint('Member', __name__, url_prefix='/member')


@routes.post('/create')
def create_member():
    database = database_connection(current_app)
    try: # making a transaction, make sure we always commit
        team_id, name = (request.form[key] for key in ('id', 'name'))
        color = request.form.get('color')
        create(database, team_id, name, color)
    except Exception as error:
        return redirect(url_for('index', error=error))
    finally:
        database.commit()

    return redirect(url_for('Team.view_team', rowid=team_id))

src/routes/run.py
from src.db.config import database_connection
from src.db.run import create, get, update_file, llsp3_file_format, modify_robot_slot, modify_title, remove

from flask import Blueprint, request, redirect, url_for, current_app
from semver import parse_version_info

import src.db.team as teams
import os


routes = Blueprint('Run', __name__, url_prefix='/run')


def prepare_file_path(group_name: str):
    group_path = os.path.join(current_app.config['LLSP3_UPLOAD_PATH'], group_name)
    if not os.path.isdir(group_path):
        os.makedirs(group_path)
    return group_path


@routes.post('/create')
def create_run():
    database = database_connection(current_app)
    try:
        team_id, robot_slot, title = (request.form[key] for key in ('id', 'robot_slot', 'title'))
        upload = request.files['upload']

        group_name = teams.get(database, team_id)['group_name']
        group_path = prepare_file_path(group_name)

        upload.save(os.path.join(group_path, llsp3_file_format(group_name, title, '0.0.1')))

        create(database, team_id, robot_slot, title)
    except Exception as error:
        return redirect(url_for('Team.view_team', rowid=team_id, error=error))
    finally:
        database.commit()

    return redirect(url_for('Team.view_team', rowid=team_id))


@routes.post('/update')
def update_run():
    database = database_connection(current_app)
    team_id, rowid = (request.form[key] for key in ('team_id', 'id'))
    try:
        upload = request.files['upload']


        group_name = teams.get(database, team_id)['group_name']
        group_path = prepare_file_path(group_name)
        run = get(database, rowid)

        version = parse_version_info(run['version'])

        version = version.bump_patch()
        if version.patch > 9:
            version = version.bump_minor()
        if version.minor > 9:
            version = version.bump_major()

        version = str(version)

        upload.save(os.path.join(group_path, llsp3_file_format(group_name, run['title'], version)))
        update_file(database, rowid, version)
    except Exception as error:
        return redirect(url_for('Team.view_team', rowid=team_id, error=error))
    finally:
        database.commit()

    return redirect(url_for('Team.view_team', rowid=team_id))

@routes.post('/modify')
def modify_run():
    database = database_connection(current_app)
    team_id, rowid = (request.form[key] for key in ('team_id', 'id'))
    try:
        robot_slot, title = (request.form.get(key) for key in ('robot_slot', 'title'))
        if robot_slot:
            modify_robot_slot(database, rowid, robot_slot)
        if title:
            modify_title(database, rowid, title)
    except Exception as error:
        return redirect(url_for('Team.view_team', rowid=team_id, error=error))
    finally:
        database.commit()

    return redirect(url_for('Team.view_team', rowid=team_id))

@routes.post('/remove')
def remove_run():
    database = database_connection(current_app)
    team_id, rowid = (request.form[key] for key in ('team_id', 'id'))
    try:
        remove(database, rowid)
    except Exception as error:
        return redirect(url_for('Team.view_team', rowid=team_id, error=error))
    finally:
        database.commit()

    return redirect(url_for('Team.view_team', rowid=team_id))

src/routes/team.py
from src.db.team import create, get, modify_group_name, modify_robot_name, remove, PUBLIC_FIELDS
from src.db.config import database_connection
from src.db.query import nav, runs

from flask import Blueprint, request, current_app, render_template, redirect, url_for

import os

routes = Blueprint('Team', __name__, url_prefix='/team')


@routes.get('/<int:rowid>')
def view_team(rowid):
    database = database_connection(current_app)
    team = get(database, rowid)
    return render_template(
        "team.html", 
        page=team['group_name'],
        team=team,
        runs=runs(database, rowid),
        nav=nav(database),
        version=current_app.config['VERSION'], 
        error=request.args.get('error'),
        modal=request.args.get('modal'),
        edit=int(request.args.get('edit', 0))
    )


@routes.post('/create')
def create_team():
    database = database_connection(current_app)
    image_upload_path = current_app.config['IMAGE_UPLOAD_PATH']
    try: # making a transaction, make sure we always commit
        group_name, robot_name = (request.form[key] for key in PUBLIC_FIELDS)
        image = request.files.get('upload')
        if image:
            if not os.path.isdir(image_upload_path):
                os.makedirs(image_upload_path)
            
            image.save(os.path.join(image_upload_path, image.filename))

        rowid = create(database, group_name, robot_name, image.filename) # ;) let's see if you can figure it out...
    except Exception as error:
        return redirect(url_for('index', error=error))
    finally:
        database.commit()

    return redirect(url_for('.view_team', rowid=rowid))


@routes.post('/modify')
def modify_team():
    database = database_connection(current_app)
    rowid = request.form['id']

    try:
        group_name, robot_name = (request.form.get(key) for key in PUBLIC_FIELDS)
        if group_name:
            modify_group_name(database, rowid, group_name)
        if robot_name:
            modify_robot_name(database, rowid, robot_name)
    except Exception as error:
        return redirect(url_for('index', error=error))
    finally:
        database.commit()

    return redirect(url_for('index'))


@routes.post('/remove')
def remove_team():
    database = database_connection(current_app)
    
    try:
        remove(database, request.form['id'])
    except Exception as error:
        return redirect(url_for('index', error=error))
    finally:
        database.commit()

    return redirect(url_for('index'))

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charset="utf-8" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
        <title>FLL VCS | {{ page | capitalize }}</title>
    </head>
    <body>
        <div id="sidenav">
            <div id="sidenav-title">
                <span><b>FLL VCS</b> | v{{ version }}</span>
                {% if page != 'Dashboard' %}
                <a href="/">Back</a>
                {% endif %}
            </div>
            {% for rowid, item in nav.items() %}
            <div class="team-item">
                <div class="team-title">
                    <div class="team-info">
                        <a href="{{ url_for('Team.view_team', rowid=rowid) }}">{{ item['name'] | capitalize }}</a>
                        <h6>- Robot: <i>{{ item['robot'] }}</i></h6>
                    </div>
                    <div class="team-count">Runs: {{ item['runs'] | length }}</div>
                </div>
                <ul class="team-runs">
                    {% for rowid, run in item['runs'].items() %}
                    <li class="team-run-row">
                        <span>[{{ run['robot_slot'] }}] {{ run['title'] | capitalize }}</span>
                        <span><a href="{{ url_for('static', filename=run['url']) }}">Download v{{ run['version'] }}</a></span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endfor %}
            <a href="https://github.com/barkerprooks/fll-dashboard">Visit the GitHub page</a>
        </div>
        <div id="content">
            {% if error %}
            <div class="error">{{ error }}</div>
            {% endif %}
            {% block content %}
            unable to load content
            {% endblock %}
        </div>
        <script src="{{ url_for('static', filename="js/main.js") }}"></script>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div id="index-title">
    <h2>All Teams</h2>
</div>
<div id="team-cards">
    {% for rowid, team in nav.items() %}
    <div class="run-item">
        <div class="run-item-title">
            {% if modal == "edit" and edit == rowid %}
            <form class="edit-inputs" method="POST" action="{{ url_for('Team.modify_team') }}" id="update-form-{{ rowid }}">
                <input style="width: 40%" name="group_name" value="{{ team['name'] }}" />
                <input style="width: 40%" name="robot_name" value="{{ team['robot'] }}" />
                <input name="id" value="{{ rowid }}" hidden />
            </form>
            {% else %}
            <h2>{{ team['name'] }}</h2>
            <h4>{{ team['robot'] }}</h4>
            {% endif %}
        </div>
        <img class="team-image" src="{{ url_for('static', filename='images/' + team['image']) }}" alt="team image"/>
        <div class="run-item-footer">
            {% if modal == "edit" and edit == rowid %}
            <div class="save-selections">
                <input class="input-button save" type="submit" form="update-form-{{ rowid }}" value="save" />
                <a style="margin-left: 12px" href="/">cancel</a>
            </div>
            <form method="POST" action="{{ url_for('Team.remove_team') }}">
                <input name="id" value="{{ rowid }}" hidden />
                <input class="input-button delete" type="submit" value="delete" />
            </form>
            {% else %}
            <a href="?modal=edit&edit={{ rowid }}">edit</a>
            <a href="{{ url_for('Team.view_team', rowid=rowid) }}">manage runs</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <div class="add-card" id="create-new">
        <small>Create a new team</small>
        <a id="create-new-button" href="?modal=create">+</a>
    </div>
</div>
{% if modal == "create" %}
<form id="modal-view" method="POST" action="{{ url_for('Team.create_team') }}" enctype="multipart/form-data">
    <div id="create-run-title">
        <h3>Create a new team</h3>
        <a href="/" class="close-button">X</a>
    </div>
    <div id="create-run-inputs">
        <input name="group_name" placeholder="Name" />
        <input name="robot_name" placeholder="Robot Name" />
    </div>
    <input name="id" value="{{ rowid }}" hidden />
    <label class="upload" for="upload">
        <input class="upload-input" id="upload" name="upload" type="file" hidden />
        <span>Upload team image here</span>
    </label>
    <input id="upload-new-run-button" type="submit" value="Create" />
</form>
{% endif %}
{% endblock %}

templates/team.html
{% extends 'base.html' %}
{% block content %}
<div id="team-title">
    <h2>{{ team['group_name'] | capitalize }}'s Runs</h2>
    <button id="upload-full-run-button">Upload full run</button>
</div>
<div id="runs">
    {% for rowid, run in runs.items() %}
    <div class="run-item">
        <div class="run-item-title">
            {% if modal == "edit" and edit == rowid %}
            <form class="edit-inputs" method="POST" action="{{ url_for('Run.modify_run') }}" id="update-form-{{ rowid }}">
                <input class="edit-input-slot" name="robot_slot" value="{{ run['robot_slot'] }}" type="number" />
                <input class="edit-input-title" name="title" value="{{ run['title'] }}" />
                <input name="id" value="{{ rowid }}" hidden />
                <input name="team_id" value="{{ team['rowid'] }}" hidden />
            </form>
            {% else %}
            <h3>{{ run['robot_slot'] }}</h3>
            <h3>{{ run['title'] | capitalize }}</h3>
            {% endif %}
        </div>
        <div class="run-item-content">
            <h5 class="run-item-version">v{{ run['version'] }}</h5>
            <form method="POST" action="{{ url_for('Run.update_run') }}" enctype="multipart/form-data">
                <label class="upload" for="update-upload-{{ rowid }}">
                    <input class="upload-input" id="update-upload-{{ rowid }}" name="upload" type="file" hidden />
                    <span style="font-size: 9pt; overflow: hidden">Update YOURFILE.llsp3 here</span>
                </label>
                <input name="id" value="{{ rowid }}" hidden />
                <input name="team_id" value="{{ team['rowid'] }}" hidden />
                <input class="update-submit-button" type="submit" value="update run" disabled />
            </form>
        </div>
        <div class="run-item-footer">
            {% if modal == "edit" and edit == rowid %}
            <div class="save-selections">
                <input class="input-button save" type="submit" form="update-form-{{ rowid }}" value="save" />
                <a style="margin-left: 12px" href="{{ url_for('Team.view_team', rowid=team['rowid']) }}">cancel</a>
            </div>
            <form method="POST" action="{{ url_for('Run.remove_run') }}">
                <input name="id" value="{{ rowid }}" hidden />
                <input name="team_id" value="{{ team['rowid'] }}" hidden />
                <input class="input-button delete" type="submit" value="delete" />
            </form>
            {% else %}
            <a href="?modal=edit&edit={{ rowid }}">edit</a>
            <a href="{{ url_for('static', filename=run['url']) }}" target="_blank">download</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <div class="add-card" id="create-new">
        <small>Create a new run</small>
        <a id="create-new-button" href="?modal=create">+</a>
    </div>
</div>
{% if modal == "create" %}
<form id="modal-view" method="POST" action="{{ url_for('Run.create_run') }}" enctype="multipart/form-data">
    <div id="create-run-title">
        <h3>Create a new run</h3>
        <a href="{{ url_for('Team.view_team', rowid=team['rowid']) }}" class="close-button">X</a>
    </div>
    <div id="create-run-inputs">
        <input name="title" placeholder="Mission Name(s)">
        <div>
            <span>Robot Slot - </span>
            <input type="number" name="robot_slot" value=1 min="1" max="20" style="width: 7ch" id="input-number" />
        </div>
    </div>
    <input name="id" value="{{ team['rowid'] }}" hidden />
    <label class="upload" for="upload">
        <input class="upload-input" id="upload" name="upload" type="file" hidden />
        <span>Upload YOURFILE.llsp3 here</span>
    </label>
    <input id="upload-new-run-button" type="submit" value="Create" />
</form>
{% endif %}
{% endblock %}